### ISSUE TITLE
CFI generation

### ISSUE THREAD

**Issue by Twibit** [readium/readium-shared-js#146] opened 2015-01-05 15:23 UTC
In my app, i have a search engine using precomputed CFI to highlight content.
In some case, our CFIs and Readium CFIs doesn't match.

Here is some example: 

```html
<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>EPUB 3.0</title>
	</head>
	<body>
		<div id="container">
			<p><a id="anchor"></a>after</p> <!-- cfi=/4/2[container]/2,/1:0,/1:5 -->
			<p><a id="anchor">inside</a>after</p> <!-- cfi=/4/2[container]/4,/2[anchor]/1:0,/4/1:5 -->
			<p><a id="anchor1"></a><a id="anchor2"></a>after</p> <!-- cfi=/4/2[container]/6,/1:0,/1:5 -->
			<p>before<a id="anchor"></a>after</p> <!-- cfi=/4/2[container]/8,/1:0,/3:5 -->
			<p>before<a id="anchor">inside</a>after</p> <!-- cfi=/4/2[container]/10,/1:0,/3:5 -->
			<p>before<a id="anchor1"></a><a id="anchor2"></a>after</p> <!-- /4/2[container]/12,/1:0,/3:5 -->
		</div>

	</body>
</html>
```

You can see in those examples that empty nodes are not always taken into account in Readium's CFIs.

In the second example Readium gives the following CFIs : 
 - cfi("inside") =  /4/2[container]/4/2[anchor],/1:0,/1:6
 - cfi("after") = /4/2[container]/4,/1:0,/1:5

You'll notice that the two CFIs are not well ordered.

**Comment by Twibit** [comment] 2015-01-07 08:41
Here is some simple examples with theoretical and actual results.
I suspect that empty text nodes are ignored in the cfi generation.

-
```html
<html>
	<p>before<a id="anchor">inside</a>after</p>
</html>
```
We should have the following results : 
**before** :  /2, /1:0, /1:6
**inside** : /2/2, /1:0, /1:6
**after** : /2, /3:0, /3:6

This specific example works with readium.

-
```html
<html>
	<p><a id="anchor">inside</a>after</p>
</html>
```
We should have results similar to the previous ones because the structure of the document didn't changes : 
**inside** : /2/2, /1:0, /1:6
**after** : /2, /3:0, /3:5

But the actual results are : 
**inside** : /2/2, /1:0, /1:6
**after** : /2, /**1**:0, /**1**:5

Note that the order isn't respected in this case : cfi("inside") > cfi("after")

-
```html
<html>
	<p><a id="anchor"></a><a id="anchor"></a>after</p>
</html>
```
We should have :
**after** : /2, /5:0, /5:5

But the actual results are : 
**after** : /2, /**1**:0, /**1**:5


-
```html
<html>
	<p>before<a id="anchor"></a><a id="anchor"></a>after</p>
</html>
```
We should have :
**before** :  /2, /1:0, /1:6
**after** : /2, /5:0, /5:5

But the actual results are : 
**inside** : /2/2, /1:0, /1:6
**after** : /2, /**3**:0, /**3**:5

**Comment by danielweck** [comment] 2015-01-07 10:29
Thank you @Twibit for taking the time to illustrate your point in detail.
This is clearly a bug, it is crucial that empty text nodes are "detected" by the CFI generator when parsing the DOM tree, i.e. implicit (potentially-empty) text node between each pair of sibling XML element, as well as before and after the first and last (respectively) child element.

**Comment by danielweck** [comment] 2015-01-07 10:35
May I suggest that this issue gets moved to the correct repository, and that relevant unit tests get added here:

https://github.com/readium/readium-cfi-js/blob/develop/spec/javascripts/models/cfi_generation_spec.js

**Comment by danielweck** [comment] 2015-01-07 10:38
Also, I suggest that @JCCR gets put in the loop as he has been working on a feature branch implementation to support further edge cases (I am not sure exactly how his work relates to this issue):

https://github.com/readium/readium-cfi-js/issues/17

**Comment by dmitrym0** [comment] 2015-01-07 16:57
@danielweck is it possible to migrate the issue into readium/readium-cfi-js or does this have to be done manually?

@Twibit the first example you provide appears to function as designed:

```html
<html>
    <p>before<a id="anchor">inside</a>after</p>
</html>
```

- `<p>` is the first non leaf node, so it's position is 2.
- `before` is the first text node of `<p>`, so it's position  is 1, and it has 6 characters, so the range is correctly identified as 1:0-1:6.
- `after` is the second text node of `<p>` so it's position is 3. It has 5 characters, so it's it's range is correctly identified at 3:0-3:5.
- `inside` is not really interesting for this example.

Your second example:

```html
<html>
    <p><a id="anchor">inside</a>after</p>
</html>
```

- `<p>` is the first non leaf node, so it's position is 2, as before
- `after` is now the first text node, so it's assigned position 1. 

This last point is where you perceive the problem to be, is that correct? It seems reasonable to expect `after` to be `3` since it follows the `<a>` element which is `2`. 

I can't find any references to this particular situation in the spec, so this does appear to be a bug with the CFI generator.

**Comment by danielweck** [comment] 2015-01-07 17:10
@dmitrym0 manual move :(   (just reference this discussion, perhaps copy/paste the essentials)

When you say "after is now the first text node, so it's assigned position 1", I think you are missing the empty text "chunk" between the `p` element and its first `a` child element (position should be 3, not 1):

http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-epubcfi-processing

"
[XML] character data that is interspersed amongst sibling child elements (i.e., "mixed content" context) is logically organised into (potentially-empty) chunks of contiguous character data: the first chunk is located before the first child element (left sibling), the last chunk is located after the last child element (right sibling), and there is one chunk between each pair of child elements. When there are no child elements, there is one (potentially-empty) chunk of character data. Consecutive (potentially-empty) chunks of character data are each assigned odd indices (i.e., starting at 1, followed by 3, etc.).
"

**Comment by dmitrym0** [comment] 2015-01-07 17:19
Ah thanks Daniel, so it is described in the spec. Definitely a bug.

**Comment by dmitrym0** [comment] 2015-01-07 17:25
Created a new issue https://github.com/readium/readium-cfi-js/issues/23, closing this one.

**Closed by dmitrym0** 2015-01-07 17:25 UTC
