### ISSUE TITLE
Repeatedly calling Reflowable_view.openPage with identical pageRequest.elementId or .elementCfi sends user to wrong location

### ISSUE THREAD

**Issue by hoppantut** [readium/readium-shared-js#261] opened 2016-02-25 13:28 UTC
Repeated calls to Reflowable_view.openPage(pageRequest) using the same pageRequest object will cause the user to be sent to the wrong location. It will transport the user further and further away from the intended location/element with each call (until the end of the chapter is reached).

The problem seems to be that the pageIndex calculation done by cfi_navigation_logic.findPageByRectangles(...) depends upon options.paginationInfo.pageOffset. The returned pageIndex is in turn used by Reflowable_view to calculate and update _paginationInfo.currentSpreadIndex, which in turn updates the _paginationInfo.pageOffset. And so with each call the pageIndex grows and causes the _paginationInfo.currentSpreadIndex to increase.

I'm not sure how this should to be dealt with correctly, but I have made a workaround by setting  _paginationInfo.pageOffset to 0 before Reflowable_view.openPage(..) pageIndex is calculated by [_navigationLogic.getPageForElementId](https://github.com/ravn-no/readium-shared-js/blob/FEATURE-EB-1231-UPDATE-READIUM/js/views/reflowable_view.js#L405) or [_navigationLogic.getPageForElementCfi](https://github.com/ravn-no/readium-shared-js/blob/FEATURE-EB-1231-UPDATE-READIUM/js/views/reflowable_view.js#L409).

Any thoughts as to how this should be fixed is appreciated.

**Comment by danielweck** [comment] 2016-02-25 13:44
I believe this is fixed in the develop branch, could you please check? (I'm assuming you are using the master branch?)

**Comment by danielweck** [comment] 2016-02-25 17:40
Oh, and what browser? Thanks :)

**Comment by hoppantut** [comment] 2016-02-26 07:24
Could you point me in the direction as to which commits you think fixed this issue?

The problem is evident in every browser I tried (chrome, firefox, IE11)

**Comment by rkwright** [comment] 2016-02-26 14:11
@hoppantut  Are you working from the master branch, the tip of develop or...  ?

**Comment by hoppantut** [comment] 2016-02-26 14:18
@rkwright Sorry, forgot to add that information. We're working on a fork of the 0.22.2 release

**Comment by danielweck** [comment] 2016-02-26 14:24
The problem described reminds of https://github.com/readium/readium-js-viewer/issues/404#issuecomment-141370059
(which has since been fixed on the development branch)

**Comment by danielweck** [comment] 2017-05-31 09:27
Fixed the regression bug ( culprit: https://github.com/readium/readium-shared-js/commit/99640b81dde92c153380bf0a57304e58279a650f ) via: https://github.com/readium/readium-shared-js/commit/9322c0afa3918db66c8e9f669377d9eca4975948
Please let us know how it goes in your tests.

**Closed by danielweck** 2017-05-31 09:27 UTC
Labels: func:CFI, func:Navigation, priority:High, type:Bug

**Comment by danielweck** [comment] 2017-05-31 10:55
Please read the follow-up:
https://github.com/readium/readium-shared-js/issues/384#issuecomment-305156108
(make sure you pull the latest code from the `develop` branch, as there is a regression bugfix)
