### ISSUE TITLE
Turn pages very slow in big html files with Android System Webview 63

### ISSUE THREAD

**Issue by fjansen** [readium/readium-shared-js#436] opened 2018-01-03 14:51 UTC
I've some epub with html file >100ko, with more than 100 pages in this file. Turn page take more than 5 seconds. I've got the last Android System Webview version : 63
If I disable Android System Webview update on my smartphone, the Android System Webview version is 55. So I turn page in the same file, it take less than 1 sec !
It's a real problem. Have you got the same issue ? A fix ? It is impossible to read this book easily.

**Comment by danielweck** [comment] 2018-01-03 15:32
Wow, that's another "interesting" regression due to Android's System Webview updates! :(
Thanks for reporting.

Are you using https://github.com/readium/SDKLauncher-Android/ (ReadiumSDK -based native app) or some custom hybrid app integration? If the latter, it would be useful to profile (via the Chrome browser's inspector / debugger) the readium-shared-js "iframe loader" (use of `document.write()` vs. `BlobURI` to load HTML documents). If this looks okay, then maybe the font-family / font-size / line-height helper (which walks the entire DOM and mutates many elements in the document) is another potential culprit. Otherwise it could be related to CSS columns, but this can easily be tested by switching to the scroll view.

**Comment by fjansen** [comment] 2018-01-03 15:52
I've tested in my app and in the last SDKLauncher-Android with the same result.
I've cleared the css in the epub, same result.
In the same app, with webview version 55 the navigation is fluid. With the last version (63) it's very slow.
In Chrome browser's inspector i've see in performance tab that "Update layer tree" take more than 3sec with webview 64. With webview 55 it take 55ms
This issue isn't with only one epub file, it's with all epub file i've try. I've try wasterland, and the navigation is slower with the last android system webview.

**Comment by danielweck** [comment] 2018-01-04 17:41
I wonder if this performance regression in Android system-wide Chrome webview is a side-effect of some CSS box model calculation or font-face loading change, that would cause the resize sensor to go into an infinite loop, or some sort of event overload. We need to trace that too.

**Comment by fjansen** [comment] 2018-01-08 10:26
I've make a little Android app with en simple webview, with html page. In the html page there is a button and an iframe. When I click on the button, I load an html page. Here the code : 
	var $iframe = document.getElementsByTagName("iframe");
	var iframeDocument = $iframe[0].contentDocument || $iframe[0].contentWindow.document;
    jQuery.get('chap_1_12.xhtml',undefined, function(data) {
        iframeDocument.body.innerHTML = data;
    },'html');

In the debug console the rendering time with Android system webview 55 is 2sec. With the last Android system webview (63) : 3,9sec.
It take double time. But in Redium time is multiplied by 5.

**Comment by danielweck** [comment] 2018-01-08 12:10
Thank you for testing this! Note that in the context of ReadiumSDK -based apps, iframes are loaded via regular `src="URL"` (no `innerHTML`):
https://github.com/readium/readium-shared-js/blob/develop/js/views/iframe_loader.js#L136

**Comment by fjansen** [comment] 2018-01-08 12:58
Oh yes, my new test with document.getElementById('iframe').setAttribute("src","chap_1_12.xhtml");
Android system webview 63 : 2sec
Android system webview 55 : between 300ms and 1sec

**Comment by danielweck** [comment] 2018-01-08 13:18
Something to try in the ReadiumSDK -based app:
https://github.com/readium/readium-shared-js/blob/develop/js/helpers.js#L256
`Helpers.UpdateHtmlFontAttributes()`
=> skip the whole function body by adding this line of code:
`callback(); return;`
...then measure HTML loading performance again.

Assuming the Android app's `reader.html` references the "single bundle" of `readium-shared-js`:
https://github.com/readium/SDKLauncher-Android/blob/develop/SDKLauncher-Android/app/src/main/assets/readium-shared-js/reader.html#L10
..then instead of re-compiling `readium-shared-js` from scratch you can simply edit the `Helpers.UpdateHtmlFontAttributes()` function in the pre-generated Javascript bundle:
https://github.com/readium/readium-shared-js/blob/develop/build-output/_single-bundle/readium-shared-js_all.js

**Comment by danielweck** [comment] 2018-01-08 13:21
Please also check the web console, and let us know if there are many "resiez sensor" messages:
https://github.com/readium/readium-shared-js/blob/develop/js/views/reflowable_view.js#L909
Thanks!

**Comment by fjansen** [comment] 2018-01-08 14:46
Thank's Daniel for your anwsers.
No change with skip.
ASW 55 : rendering 54ms, scripting 400-450ms
ASW 63 : rendering 3400ms, scripting 250-300ms

And there's no message from "resize sensor" in the web console...

**Comment by fjansen** [comment] 2018-01-12 14:06
Have you see the same thing in the adroid launcher ?

**Comment by danielweck** [comment] 2018-01-23 16:41
Device:
Nexus 6P
(latest Android `8.1.0`)

Chrome web browser (app disabled):
`61.0.3163.98` (system-shipped minimum base version)

Android System WebView (enabled, checked in developer options):
`63.0.3239.111` (latest from Google PlayStore)

Test ePUB: "Children's Literature" from:
https://idpf.github.io/epub3-samples/30/samples.html
There single spine item is a long reflowable HTML document (250+ pages / CSS columns, in portrait mode)
=> 10s+ (seconds) to initially load
=> 6s+ to turn pages (irrespective of the current location in the page flow)

Note that iBooks on OSX also takes a HUUGE amount of time to load it, in fact it is very comparable to SDKLauncher-Android my Android phone. This is one of my test books for Readium2 "navigator" / Electron app (`r2-testapp-js` and `readium-desktop`), and it is slow there as well (albeit not as bad as iBooks).

If I uninstall the Android System WebView, the earliest I can go back to is version `61.0.3163.98` (same as the default system-shipped Chrome web browser). When I rollback, apps that rely on the system-wide Chromium webview *crash* during bootup (e.g. Amazon, SDKLauncher-Android, see logcat dump below). So, I am not able to test anything with the "older" version (never mind, as I cannot go back all the way to v55 anyway).

So, I will test only the latest version of Android System WebView, hoping I can pin-point the culprit for this performance drop. Let's see...

**Comment by danielweck** [comment] 2018-01-23 16:44
`"/system/app/Chrome/Chrome.apk!/lib/arm64-v8a/libmonochrome.so" is 64-bit instead of 32-bit`
=>
```
    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:208)
    ... 39 more
Caused by: java.lang.RuntimeException: Cannot load WebView
    at com.android.webview.chromium.WebViewChromiumFactoryProvider.initialize(WebViewChromiumFactoryProvider.java:71)
    at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:36)
    at com.android.webview.chromium.WebViewChromiumFactoryProviderForO.<init>(WebViewChromiumFactoryProviderForO.java:4)
    at com.android.webview.chromium.WebViewChromiumFactoryProviderForOMR1.<init>(WebViewChromiumFactoryProviderForOMR1.java:5)
    at com.android.webview.chromium.WebViewChromiumFactoryProviderForOMR1.create(WebViewChromiumFactoryProviderForOMR1.java:1)
    ... 41 more
Caused by: org.chromium.base.library_loader.ProcessInitException
    at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:91)
    at org.chromium.base.library_loader.LibraryLoader.loadNowOverrideApplicationContext(LibraryLoader.java:27)
    at com.android.webview.chromium.WebViewChromiumFactoryProvider.initialize(WebViewChromiumFactoryProvider.java:65)
    ... 45 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/system/app/Chrome/Chrome.apk!/lib/arm64-v8a/libmonochrome.so" is 64-bit instead of 32-bit
    at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
    at java.lang.System.loadLibrary(System.java:1657)
    at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:75)
```

**Comment by danielweck** [comment] 2018-01-23 17:13
Chrome profiler, 5s of "Update Layer Tree":

![sdklauncher-android_chromiumprofile_updatelayertree](https://user-images.githubusercontent.com/625201/35289967-bbdc08f6-0060-11e8-8c1c-01e815ae2307.png)

**Comment by danielweck** [comment] 2018-01-23 17:14
The few milliseconds before (CFI processing, as expected):
![sdklauncher-android_chromiumprofile_before](https://user-images.githubusercontent.com/625201/35289993-cc78ea9e-0060-11e8-84c3-94dab8c7da17.png)

**Comment by danielweck** [comment] 2018-01-23 17:14
The few milliseconds after (CFI processing, as expected):
![sdklauncher-android_chromiumprofile_after](https://user-images.githubusercontent.com/625201/35290018-dbb95dfe-0060-11e8-9523-a318f48fcca9.png)

**Comment by danielweck** [comment] 2018-01-23 17:15
So, during "page turn" (viewport shift to reveal adjacent CSS columns), we must make sure *not* to trigger a layout/render pass ... I'm looking into this now. Ideas welcome.

**Comment by danielweck** [comment] 2018-01-23 17:21
Well, https://productforums.google.com/forum/#!topic/chrome/cg3fh2lkViM

**Comment by danielweck** [comment] 2018-01-23 17:55
Let's ignore Android for a moment.

I tested "Children's Literature" in Chrome on OSX (`63.0.3239.132`) using the Readium Chrome offline app / extension, and the online web/cloud reader. Both initial load/render times and page-turn delays are significant, given the available processing power on a desktop computer. The performance drop is not as prohibitive as on Android, but it is very perceivable nonetheless.

More importantly, page-turns on Firefox and Safari are *instant*! (initial load time is still on the high side, but not as bad as Chrome).

The Brave (Electron-based) web browser v`0.19.105` based on Chromium `62.0.3202.94` has instant page-turns too. Once updated to v`0.19.139` (Chromium `64.0.3282.85`, see https://github.com/brave/browser-laptop/releases/tag/v0.19.139dev ), page-turns are also instant. However, rollback to v`0.19.121` (Chromium `63.0.3239.108`, see https://github.com/brave/browser-laptop/releases/tag/v0.19.121dev ), then page-turns are horribly slow again!

Try for yourself:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2FIDPF%2Fepub3-samples%2Fmaster%2F30%2Fchildrens-literature&epubs=epub_content%2Fidpf_samples.opds

Conclusion: there is a performance-related regression bug in Chromium 63.x. This bug is fixed in Chromium 64.x, and with a bit of luck maybe this will be addressed in the Chromium v63 release branch at some point soon too.

**Comment by danielweck** [comment] 2018-01-23 18:26
So far, I have not been able to pin-point code in `readium-shared-js` that could potentially be merely *adjusted* in order to work around Chromium's regression bug, such as implementing a small variation on the current document rendering/reflow strategy that would somehow result in not triggering the "Update Layer Tree" pass in the browser engine, during "page turns" (i.e. CSS Column shifts on the horizontal axis, see https://github.com/readium/readium-shared-js/blob/dd645d38f8c29e01b386cd2b2864379358e91ed6/js/views/reflowable_view.js#L570 ). Who knows, this could be as simple as introducing a trick CSS property (or modifying an existing one) that would somehow restore Chromium's renderer sanity when displaying long column-ized HTML documents ... but I have not been lucky thus far.

One option would be to try using `overflow:scroll` and `scrollOffset` instead of manipulating absolute coordinates at the document level (HTML root element). I believe @JCCR looked into this a while back, so he may be able to advise. I believe this would be a significant design refactoring (e.g. as Readium iframes have fixed viewport dimensions, documents hosted inside iframes would need to scroll their own column-ized content ... which sounds tricky). Such change would probably impact Right-To-Left and Vertical-Writing-Mode handling quite significantly. We should not underestimate the amount of testing required to assert whether this would be safe to ship in apps across all combinations of target platforms and browsers / webviews.

Thoughts welcome.

**Comment by danielweck** [comment] 2018-01-23 18:46
Here is a simple repro test case that does not require Readium at all:

1) open Chrome (web browser)
2) load URL `https://cdn.rawgit.com/IDPF/epub3-samples/master/30/childrens-literature/EPUB/s04.xhtml`
3) "inspect" document (launch debugging console)
4) copy+paste and execute command: `document.documentElement.setAttribute("style", "height: 600px; min-height: 600px; max-height: 600px; position: relative; margin: 0px; padding: 0px; column-gap: 60px; font-size: 100%; border: 0px; width: 600px; columns: auto 2; column-fill: auto; top: 0px; left: 0px;");`
5) copy+paste and execute command: `document.documentElement.style.left=(parseInt(document.documentElement.style.left)-660)+"px"` (this simply shifts the document in order to hide one column width on the left / reveal an additional column on the right)
6) (use `document.documentElement.style.left=0` to reset)
7) see how much time the render pass takes ...

Now, try this again with Safari or Firefox => the document's horizontal shift is instant.

**Comment by llemeurfr** [comment] 2018-01-23 19:20
Thanks Daniel, great study! 
I tried to follow your last comment on my Mac, with Chrome 63.0.3239.132: the column navigation is fluid, i.e. 1/2 sc to render the new columns. But I also perceived some lag on Children's litterature using the firebase link, when comparing pagination of Chrome (3/4 sc maybe) vs Firefox (instant).

**Comment by llemeurfr** [comment] 2018-01-23 19:24
Is it possible to test Chromium v64 on Android already?

**Comment by danielweck** [comment] 2018-01-23 20:08
yes, Chrome dev is 65, Chrome beta is 64.

**Comment by danielweck** [comment] 2018-01-23 20:14
On Android, Chrome (63) exhibits the problem. Chrome-Beta (64) does not.
This observation aligns with my other findings.
Test link:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2FIDPF%2Fepub3-samples%2Fmaster%2F30%2Fchildrens-literature&epubs=epub_content%2Fidpf_samples.opds

**Comment by danielweck** [comment] 2018-01-30 13:44
It seems that Chromium v64 (stable) has been pushed to all channels by Google on January 25th (Android system WebView, and Chrome web browser for all platforms).
Closing.

**Closed by danielweck** 2018-01-30 13:45 UTC
Labels: difficulty:Dev, func:Layout, platform:Android, priority:High, type:Bug
