### ISSUE TITLE
trigger event stoppropagation

### ISSUE THREAD

**Issue by kimtuck** [readium/readium-shared-js#339] opened 2016-11-11 17:56 UTC
Markup can contain a <epub:trigger tag.  For example a click event.  If the element is clicked, the handler in trigger.js correctly handles the event, but allows the event to bubble up.  In my (hybrid) reader, you can click on the page's left side to move back a page; and click on the right side to move forward a page.  If the event handler allows the click event to bubble up, then immediately after the event is handled, the user moves to a different page.

I believe the intent of the trigger tag is to perform some action on the page, and then stop.  I'll make a pull request with a patch that stops the event bubbling up.

**Comment by kimtuck** [comment] 2016-11-11 18:08
Daniel, I'd like to post a pull request for this fix, but don't know how to go about it.  If I try to push my branch, it gives me a 403 error.  Please let me know the correct procedure for pushing branches/pull requests.

**Comment by danielweck** [comment] 2016-11-12 17:09
I believe this is a duplicate of 
https://github.com/readium/readium-js-viewer/issues/582
right?
      
Do you have write-access to the readium-shared-js repository? If not, you can just create a PR from the Github website, when logged into your account, and when viewing the branch in your fork.

**Comment by danielweck** [comment] 2016-11-12 17:10
https://github.com/readium/readium-shared-js/compare/develop...feature/prefetch

**Closed by danielweck** 2016-11-12 17:10 UTC

**Comment by kimtuck** [comment] 2016-11-21 17:56
Hi Daniel,

I’m getting a 403 error when I try to push a branch to the repo.  So I’ll try this another way.

If what I’m reading is correct, what I need to do is
A) fork the readium-shared-js repo into my own account
B) make branches in my fork, commit and push the changes back to my fork
C) Create a pull request; which will allow you to pull my code.

I’ve lookup up this procedure on the interwebs and it sounds like it will work.

**Comment by danielweck** [comment] 2016-11-21 18:38
Sounds good. Thanks!

**Comment by rkwright** [comment] 2016-11-21 21:42
Yes, you do not have permissions to push commits to our repos.  In general, we discourage EVERYONE (except Daniel and a couple of other long-time contributors) from committing directly.  It is much better practice for everyone to do so via pull-request.  Thanks for your patience and contributions.
