### ISSUE TITLE
In some spine items, the last page of a chapter is skipped

### ISSUE THREAD

**Issue by rkwright** [readium/readium-shared-js#193] opened 2015-07-07 20:48 UTC
A company building a viewer for iOS using their own back-end and shared-js with their own UI has discovered that in some spine items, the last partial page of the spine item is skipped. Apparently, readium thinks the chapter is one page less than it really is (and would be laid out).
## Turns out that others have seen this sporadically.  Hard to reproduce.

From Brian Young:
Thanks again for your help on Monday. Over the course of the week I was able to identify one of the possibilities you mentioned as the probable culprit: a timing issue relating to the use of @font-face declarations.

The problem

In certain chapters, with certain font size settings, when re-paginating the spine, the last page of the chapter is cut off. So in a chapter that should have 22 pages, the app thinks there are only 21 pages in the chapter.

We're running our own fork of readium-shared-js inside of an iOS WKWebView. 

Analysis so far

We loaded the book "Pale Gray for Guilt" in our local readium-js-viewer instance running in Safari Version 8.0.6 (10600.6.3) on the Macbook, and were not able to reproduce the issue.

Then, we ran our app in the iPhone 6 Simulator, and used Safari dev tools to place break points at various lines in reflowable_view.js file and other relevant files, and inspected the scrollHeight and scrollWidth values computed by the browser. 

We found that on the chapters in question, the scrollHeight and scrollWidth values are a little too small when columnCount is calculated, causing the columnCount (i.e. the number of pages in the chapter) to be one page too small after rounding.

Interestingly, we found that when we placed a break point at one line in particular (line 227 of reflowable_view.js), and then stepped through the code for the next two lines, the bug did not appear: the scrollHeight and scrollWidth values of the _$epubHtml body were correct. Then, if we silence the break points and let the code run unimpeded, the bug would reappear.

So, it seemed to be something to do with timing. So, we created a little "sleep" function, put it at line 227 (and others nearby), and crossed our fingers. Unfortunately, the bug still appeared. 

Then, I remembered what you had said about @font-face declarations. I checked the book in question, and sure enough we're loading fonts from the local disk, but using @font-face to do it. So, following your advice, I merged Juan's pull request #179 into our fork, and ran it locally. 

While this is promising, I'm finding that the code doesn't seem work yet in our app: I'm not sure exactly why, but when the app tries to execute line 102 of FontLoader.js – calling document.createElement("div") – the resulting element's "style" member, which should be a CSSStyleDeclaration object, is null. 

I'm not sure if this is because of a quirk in WKWebview's implementation, or in my usage of the Juan's font loader library, so I'm continuing to work through the problem, trying to get it to work in our project.

Questions for Readium:

Do you have any further thoughts or explanation as to what the underlying cause might be?

Do you have another suggestion as to how to resolve it, short of using Juan's fix?

Please let me know if you want to chat, or if you need any more information; also I'm happy to send you an example ePub that shows the problem if that would help.

**Comment by dmitrym0** [comment] 2015-07-08 15:38
We've seen this before, specifically in #182. Looks like the pagination isn't finished when the layout info is generated. @JCCR may have more info.

**Comment by bpyoung** [comment] 2015-07-28 16:25
Hey @rkwright, @danielweck and @JCCR ,

Since the last time we spoke on this subject, I loaded one of the problematic books in the iOS sample project and was able to reproduce the issue. Let me know if you want to dig into it on your own and I'll send you an example ePub.

Thanks
Brian

**Comment by JCCR** [comment] 2015-07-28 17:07
FontLoader.js comes from this project (it does most of the "magic"): https://github.com/smnh/FontLoader

Unfortunately I couldn't use it as-is. It had to be modified to support our use of a different iframe document context. 

@rkwright It appears to be MIT licensed, so looks like we are good on the licensing aspect.

In order for us to better track this, we can either do what @danielweck does, which is fork the repo and include it as an npm package via git. Or I can submit a PR with these and any further fixes/modifications to the original repo.

**Comment by rkwright** [comment] 2015-07-28 17:29
@JCCR  Sounds reasonable, but let's figure out the solution to the missing-page bug first.  Then revisit the issue with the licensed third-party library.

**Comment by danielweck** [comment] 2015-07-29 09:48
@JCCR Why not fork the repo AND submit a PR? :) (as opposed to OR)
The `npm run prepare` pre-build script checks for updated upstream code for each forked library dependency, which helps monitoring PR merges, release updates, etc.

@bpyoung Thank you very much for the follow-up / tests. Could you please share the EPUB? (privately if necessary)

**Comment by JCCR** [comment] 2015-08-05 18:53
@danielweck Looks like I already did this back in april: https://github.com/smnh/FontLoader/pull/8

Silly of me to forget :)

**Comment by JCCR** [comment] 2015-08-05 19:54
This is neat:
http://caniuse.com/#feat=font-loading

Looks like its finally in chrome!

**Comment by rkwright** [comment] 2015-08-05 20:06
Yes, but there is a lot of red on that page as well.  Like in iOS/OSX

**Comment by JCCR** [comment] 2015-08-05 21:23
@rkwright 
Yea that is correct. Webkit's implementation is still a WIP.

I'm going to use this if available and use the other method as a fallback.

@danielweck 
I just found out that my PR code doesn't work at all because of CORS...
My method relies on .cssRules being available:
http://stackoverflow.com/questions/3211536/accessing-cross-domain-style-sheet-with-cssrules

**Comment by JCCR** [comment] 2015-08-05 21:29
@danielweck 
Helpers.triggerLayout also breaks because of this.

**Comment by danielweck** [comment] 2015-08-06 11:36
Thanks @JCCR about the `.cssRules` issue! Would `XmlHTTPRequest.responseText` + injection in `style` tag work, instead of CSSOM? (or are there other external references that need to be resolved relatively to the base CSS? ... I haven't looked at the details of the FontLoader trick)

**Comment by JCCR** [comment] 2015-08-06 21:28
@danielweck 
That would work too but I didn't want to head in that direction, there's already some stuff that we do with style tags such as preprocessing and mangling the stylesheet content for obfuscated fonts. 

One thing that CSSOM won't help us with is if the CSS files include other CSS stylesheets via the @import rule.
I'm not sure how that would work if we ajax request and inject those particular stylesheets as well. The referenced stylesheets could be treated as an external resource and be restricted as well, or not resolved properly in the first place.

I'm going to do some investigation on this.

**Comment by JCCR** [comment] 2015-08-06 21:40
@danielweck 
Here's how the font loading stuff works:

**If [CSS Font Loading](https://drafts.csswg.org/css-font-loading/) is not implemented:**
- We need to get a list of all external fonts that a document uses:
This is done by looking at the parsed stylesheets in the DOM. All the cssRules for FontFace declarations are found, and the font family names are extracted from that to build the list.
- Once the list of all referenced font families are found we need to reduce to the ones that are actually used in the styles of the document. It could be that there is a common stylesheet included in many documents, with many fonts defined but only a few used in each particular document.
This is done by looking at all the calculated CSS properties for the document elements and finding font-family declarations.
- After the list of used font families are found we can pass it over to the smnh/FontLoader library. It will then do its magic to find out when the fonts are ready and loaded.

**If it is implemented:** (Only in chrome right now)
We simply use it with a small amount of logic around it :)
We dont have to find out which fonts are used. We don't have to work around the cross-domain issues. It just works. Plus the spec even claims to only fire the ready event when the text is fully laid out too, so that's a big plus for finding the last state for pagination.

**Comment by JCCR** [comment] 2015-08-06 22:22
@danielweck 
Ok I don't need to worry about the `@import` rules with my current approach because the document.styleSheets list I'm using contains an absolute href for each linked stylesheet, no matter how it was included.

**Comment by rflechner** [comment] 2016-03-02 12:02
Hi,

I had the same problem in safari and IOS.
The problem is in FontLoader.js
this._document was an iframe and create an element generated a null value for style property.
I replaced all this._document.createElement by document.createElement, then the style property was correctly set.

All is working for me now.

Regards

**Comment by danielweck** [comment] 2016-03-02 15:36
Thanks @rflechner 

So, FontLoader is an external library dependency that ReadiumJS currently fetches from `smnh/FontLoader`:
https://github.com/smnh/FontLoader
...see:
https://github.com/readium/readium-shared-js/blob/develop/package.cson#L126

It's used in `readium-shared-js` > `js/views/font_loader.js`:
https://github.com/readium/readium-shared-js/blob/develop/js/views/font_loader.js#L28

The `FontLoader` instance is created with the correct `document`, as far as I can tell:
https://github.com/readium/readium-shared-js/blob/develop/js/views/font_loader.js#L124
...see:
`function FontLoader(fonts, delegate, timeout, contextDocument) {}` > `this._document = contextDocument || document;`
https://github.com/smnh/FontLoader/blob/master/FontLoader.js#L66

**Comment by danielweck** [comment] 2016-03-02 15:38
...so, how is it possible that "this._document was an iframe"?

**Comment by rflechner** [comment] 2016-03-02 15:45
Hi,

When we use the DOM inspector on a readium web page,  we can see the is displayed in an iframe.
It seems the document passed to the FontLoader is an Iframe.
( see. https://github.com/readium/readium-shared-js/blob/master/js/views/reflowable_view.js#L220 )

Regards

**Comment by danielweck** [comment] 2016-03-02 17:12
@rflechner you are looking at the wrong FontLoader (see my comment above):

https://github.com/smnh/FontLoader/blob/master/FontLoader.js
vs.
https://github.com/readium/readium-shared-js/blob/develop/js/views/font_loader.js
(which uses `smnh/FontLoader` linked above)

**Comment by rflechner** [comment] 2016-03-03 09:26
Woups, sorry for mistake.

So, this._document was not an iframe, but create an element from it generated a null value for style property.

Regards

**Comment by danielweck** [comment] 2017-02-03 14:13
This was fixed with the replacement of FontLoader with ResizeSensor, now available in the latest official release v0.25

**Closed** 2017-02-03 14:13 UTC
Labels: func:Layout, priority:High, type:Bug
