### ISSUE TITLE
range cfi parse error

### ISSUE THREAD

**Issue by JackieFei** [readium/readium-shared-js#344] opened 2016-11-16 11:52 UTC
#### Related issue(s) and/or pull request(s)
See also #313

#### Expected Behaviour
get the range successfully

#### Observed behaviour
tested with 2 equivalent range cfi, but one failed

#### Steps to reproduce
1. open https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3&
2. open the developer tool console
3. make sure the range cfi is correct, enter the commands manually
> ReadiumSDK.reader.getDomRangeFromRangeCfi({idref: "id-id2442754", contentCFI: "/4/2[I_book_d1e1]/2,/1:0,/1:1"})
>> got a range
4. change to another equivalent range cfi (move parent cfi partials to start cfi and end cfi)
> ReadiumSDK.reader.getDomRangeFromRangeCfi({idref: "id-id2442754", contentCFI: "/4,/2[I_book_d1e1]/2/1:0,/2[I_book_d1e1]/2/1:1"})
>> Uncaught : Expected "!/", "/", "[", or [0-9] but "," found.

**Comment by danielweck** [comment] 2016-11-17 07:38
Note that the `goto` URL parameter can be used to directly reference an "open page request", such as the aforementioned CFI / JSON:
`{"idref":"id-id2442754","elementCfi":"/4/2[I_book_d1e1]/2,/1:0,/1:1"}`
(differences: `elementCfi` instead of `elementCFI`, no spaces around `:` and `,` separators, and mandatory quotes `"` around JSON keys / property names)

=> then, we URL-encode the "goto" parameter:
`%7B%22idref%22%3A%22id-id2442754%22%2C%22elementCfi%22%3A%22%2F4%2F2%5BI_book_d1e1%5D%2F2%2C%2F1%3A0%2C%2F1%3A1%22%7D`

=> resulting URL:
https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3&goto=%7B%22idref%22%3A%22id-id2442754%22%2C%22elementCfi%22%3A%22%2F4%2F2%5BI_book_d1e1%5D%2F2%2C%2F1%3A0%2C%2F1%3A1%22%7D

When this link is opened, there is a temporary yellow highlighting of the referenced character (in this case: top-left "A").

**Comment by danielweck** [comment] 2016-11-17 07:42
Now, I am also able to reproduce the bug:

`{"idref":"id-id2442754","elementCfi":"/4,/2[I_book_d1e1]/2/1:0,/2[I_book_d1e1]/2/1:1"}`
should be equivalent to
`{"idref":"id-id2442754","elementCfi":"/4/2[I_book_d1e1]/2,/1:0,/1:1"}`

...but this URL fails to open to the correct location:
https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3&goto=%7B%22idref%22%3A%22id-id2442754%22%2C%22elementCfi%22%3A%22%2F4%2C%2F2%5BI_book_d1e1%5D%2F2%2F1%3A0%2C%2F2%5BI_book_d1e1%5D%2F2%2F1%3A1%22%7D

The console error is:
"SyntaxError: Expected "!/", "/", "[", or [0-9] but "," found."

This therefore seems to be an issue with the CFI parser itself:
PegJS grammar:
https://github.com/readium/readium-cfi-js/blob/develop/cfi_parser.pegjs#L41
Generated parser code:
https://github.com/readium/readium-cfi-js/blob/develop/gen/cfi_parser_gen.js#L1

**Comment by danielweck** [comment] 2016-11-17 08:05
@JCCR the production rule for "range" is wrong, because it *requires* `indexStep` to be followed with `local_path` (which recursively includes `indexStep`), which prevents the "shared root" of a CFI range expression to be a simple "/4" (as per the example in this bug report):
https://github.com/readium/readium-cfi-js/blob/develop/cfi_parser.pegjs#L49
```
range = stepVal:indexStep localPathVal:local_path "," rangeLocalPath1Val:local_path "," rangeLocalPath2Val:local_path 
```

A good way to test this is to try: `ReadiumSDK.reader.getDomRangeFromRangeCfi({idref: "id-id2442754", contentCFI: "/4/2[I_book_d1e1],/2/1:0,/2/1:1"})`
=> it works

...but this doesn't work:
ReadiumSDK.reader.getDomRangeFromRangeCfi({idref: "id-id2442754", contentCFI: "/4,/2[I_book_d1e1]/2/1:0,/2[I_book_d1e1]/2/1:1"})

So, we could fix this bug by making `localPathVal:local_path` optional.

**Comment by danielweck** [comment] 2016-11-17 08:12
@JCCR I added "optionality", and it all seems to work fine. I am pushing the bugfix.

**Comment by danielweck** [comment] 2016-11-17 08:16
Fixed in `readium-cfi-js`:
https://github.com/readium/readium-cfi-js/commit/d5a4928df5e4d3b3a30947ef1a633ab2c6760608
(I will let you know when the updated cloud reader app is deployed to Firebase)

**Comment by danielweck** [comment] 2016-11-17 08:20
TravisCI building now...
https://travis-ci.org/readium/readium-js-viewer/builds/176628487

**Comment by danielweck** [comment] 2016-11-17 08:25
While TravisCI is building the cloud reader app, here are test URLs (to be verified once the build is completed):

(note that when each link is opened, there should be a temporary yellow highlighting for the referenced character, which in this case is the top-left "A")

TEST 1 (this always worked)
`{"idref":"id-id2442754","elementCfi":"/4/2[I_book_d1e1]/2,/1:0,/1:1"}`
=>
https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3&goto=%7B%22idref%22%3A%22id-id2442754%22%2C%22elementCfi%22%3A%22%2F4%2F2%5BI_book_d1e1%5D%2F2%2C%2F1%3A0%2C%2F1%3A1%22%7D

TEST 2 (this one failed because of the single shared root XML step)
`{"idref":"id-id2442754","elementCfi":"/4,/2[I_book_d1e1]/2/1:0,/2[I_book_d1e1]/2/1:1"}`
=>
https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3&goto=%7B%22idref%22%3A%22id-id2442754%22%2C%22elementCfi%22%3A%22%2F4%2C%2F2%5BI_book_d1e1%5D%2F2%2F1%3A0%2C%2F2%5BI_book_d1e1%5D%2F2%2F1%3A1%22%7D

TEST 3 (this one always worked)
`{"idref":"id-id2442754","elementCfi":"/4/2[I_book_d1e1],/2/1:0,/2/1:1"}`
=>
https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3&goto=%7B%22idref%22%3A%22id-id2442754%22%2C%22elementCfi%22%3A%22%2F4%2F2%5BI_book_d1e1%5D%2C%2F2%2F1%3A0%2C%2F2%2F1%3A1%22%7D

**Comment by danielweck** [comment] 2016-11-17 08:27
Tested.

**Closed by danielweck** 2016-11-17 08:27 UTC
Labels: difficulty:Guru, func:CFI, type:Bug

**Comment by JCCR** [comment] 2016-11-22 00:07
@danielweck 
Thanks for the fix.

I didn't notice this thread until now
